language: node_js

sudo: false

node_js:
- 8.11.1

branches:
  only:
  - hexo

git:
  submodules: false

before_install:
- openssl aes-256-cbc -K $encrypted_a4dcfa5f2d9a_key -iv $encrypted_a4dcfa5f2d9a_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'Richard-Cao'
- git config --global user.email '403164405@qq.com'
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- ssh-agent -k

install:
- travis_wait npm install hexo-cli -g
- travis_wait npm install
- git submodule init
- git submodule update
- cd themes/next
- git clone https://github.com/theme-next/theme-next-canvas-nest source/lib/canvas-nest
- git clone https://github.com/theme-next/theme-next-han source/lib/Han
- git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
- git clone https://github.com/theme-next/theme-next-pangu.git source/lib/pangu
- git clone https://github.com/theme-next/theme-next-pace source/lib/pace
- cd $HOME/build/Richard-Cao/Richard-Cao.github.io

script:
- hexo clean
- hexo g
- hexo d
