language: node_js

sudo: false

node_js:
- 6.11.1

branches:
  only:
  - hexo

git:
  submodules: false

before_install:
- openssl aes-256-cbc -K $encrypted_a4dcfa5f2d9a_key -iv $encrypted_a4dcfa5f2d9a_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'Richard-Cao'
- git config --global user.email '403164405@qq.com'
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- ssh-agent -k

install:
- travis_wait npm install hexo-cli -g
- travis_wait npm install

script:
- git submodule init
- git submodule update
- hexo clean
- hexo g
- hexo d
