# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lifecycle
subtitle: 真正的梦就是现实的彼岸。
description: 不积小流，无以成江海。
author: RichardCao
language: zh-Hans
timezone:
avatar: http://7xr0xq.com1.z0.glb.clouddn.com/%E5%9B%9B%E4%BB%A3.jpg
since: 2015

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://richard-cao.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
stylus:
  compress: true

# Local Search
search:
  path: search.xml
  field: post

# Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#Social links
social:
  github: https://github.com/Richard-Cao

# duoshuo
duoshuo_shortname: richardcao
duoshuo_hotartical: true
duoshuo_share: true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Richard-Cao/Richard-Cao.github.io.git
  branch: master
